global:
  scrape_interval: 15s # как часто опрашивать exporter-ы

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'app'
    static_configs:
      - targets: ['grpcapi:9990']
  - job_name: 'db'
    static_configs:
      - targets: ['pg_exporter:9187']
