server:
  httplisten:  "localhost:8080"

log:
  encoding:     "json"
  outputpaths:
    - "log/app.log"
  level:        "debug"
  initialfields:
    app:        "api"

db:
  dsn:          "host=localhost port=5401 user=postgres dbname=postgres password=postgres sslmode=disable"

repository:
  type:       "inmemory"