server:
  httplisten:  "localhost:8080"

log:
  encoding:     "json"
  outputpaths:
    - "log/app.log"
  level:        "debug"
  initialfields:
    app:        "api"

db:
  dsn:          ""

repository:
  type:       "inmemory"