server:
  httplisten:                 "0.0.0.0:8881"
  grpclisten:                 "0.0.0.0:8882"
  http_for_prometheus_listen: "0.0.0.0:9990"

log:
  encoding:     "json"
  outputpaths:
    - "stdout"
    - "log/app.log"
  level:        "debug"
  initialfields:
    app:        "calendar"

db:
  dialect:      "postgres"
  dsn:          "host=localhost port=5432 dbname=postgres user=postgres password=postgres sslmode=disable"

queue:
  rabbitmq:
    consumer_tag:   "sender"
    uri:            "amqp://guest:guest@localhost:5672"
    exchange_name:  "calendar.Notice"
    exchange_type:  ""
    queue:          "calendar.Notice"
    binding_key:    "calendar.Notice"

  rabbitmqusernotification:
    consumer_tag:   "notificationSender"
    uri:            "amqp://guest:guest@localhost:5672"
    exchange_name:  "calendar.UserNotice"
    exchange_type:  ""
    queue:          "calendar.UserNotice"
    binding_key:    "calendar.UserNotice"

jwt_signing_key: "LxsKJywDL5O5PvgODZhBH12KE6k2yL8E"
jwt_expiration: 72
